#############################################################################
# Makefile for building: practica
# Generated by qmake (2.01a) (Qt 4.7.4) on: Fri May 11 12:17:16 2012
# Project:  practica.pro
# Template: app
# Command: /home/lain/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile practica.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ -I. -I../../QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/474/gcc/include/QtOpenGL -I../../QtSDK/Desktop/Qt/474/gcc/include -I/usr/X11R6/include -I.moc -I.ui
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/lain/QtSDK/Desktop/Qt/474/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/lain/QtSDK/Desktop/Qt/474/gcc/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/lain/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = cameraIDI.cpp \
		glwidget.cpp \
		model.cpp \
		objectInstance.cpp \
		scene.cpp \
		face.cpp \
		vertex.cpp \
		color.cpp \
		box.cpp \
		XML.cpp \
		ground.cpp \
		material.cpp \
		material_lib.cpp \
		point.cpp \
		tinystr.cpp \
		tinyxml.cpp \
		tinyxmlerror.cpp \
		tinyxmlparser.cpp \
		main.cpp \
		principal.cpp .moc/moc_glwidget.cpp \
		.moc/moc_principal.cpp
OBJECTS       = .obj/cameraIDI.o \
		.obj/glwidget.o \
		.obj/model.o \
		.obj/objectInstance.o \
		.obj/scene.o \
		.obj/face.o \
		.obj/vertex.o \
		.obj/color.o \
		.obj/box.o \
		.obj/XML.o \
		.obj/ground.o \
		.obj/material.o \
		.obj/material_lib.o \
		.obj/point.o \
		.obj/tinystr.o \
		.obj/tinyxml.o \
		.obj/tinyxmlerror.o \
		.obj/tinyxmlparser.o \
		.obj/main.o \
		.obj/principal.o \
		.obj/moc_glwidget.o \
		.obj/moc_principal.o
DIST          = ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		practica.pro
QMAKE_TARGET  = practica
DESTDIR       = 
TARGET        = practica

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .ui/ui_principal.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: practica.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++/qmake.conf ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile practica.pro
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile practica.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/practica1.0.0 || $(MKDIR) .obj/practica1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/practica1.0.0/ && $(COPY_FILE) --parents cameraIDI.h glwidget.h model.h objectInstance.h scene.h face.h vertex.h color.h box.h XML.h ground.h material.h material_lib.h point.h tinystr.h tinyxml.h principal.h .obj/practica1.0.0/ && $(COPY_FILE) --parents cameraIDI.cpp glwidget.cpp model.cpp objectInstance.cpp scene.cpp face.cpp vertex.cpp color.cpp box.cpp XML.cpp ground.cpp material.cpp material_lib.cpp point.cpp tinystr.cpp tinyxml.cpp tinyxmlerror.cpp tinyxmlparser.cpp main.cpp principal.cpp .obj/practica1.0.0/ && $(COPY_FILE) --parents principal.ui .obj/practica1.0.0/ && (cd `dirname .obj/practica1.0.0` && $(TAR) practica1.0.0.tar practica1.0.0 && $(COMPRESS) practica1.0.0.tar) && $(MOVE) `dirname .obj/practica1.0.0`/practica1.0.0.tar.gz . && $(DEL_FILE) -r .obj/practica1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_glwidget.cpp .moc/moc_principal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_glwidget.cpp .moc/moc_principal.cpp
.moc/moc_glwidget.cpp: material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h \
		glwidget.h
	/home/lain/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o .moc/moc_glwidget.cpp

.moc/moc_principal.cpp: .ui/ui_principal.h \
		glwidget.h \
		material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h \
		principal.h
	/home/lain/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) principal.h -o .moc/moc_principal.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: .ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .ui/ui_principal.h
compiler_uic_clean:
	-$(DEL_FILE) .ui/ui_principal.h
.ui/ui_principal.h: principal.ui \
		glwidget.h \
		glwidget.h \
		material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h \
		material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h
	/home/lain/QtSDK/Desktop/Qt/474/gcc/bin/uic principal.ui -o .ui/ui_principal.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

.obj/cameraIDI.o: cameraIDI.cpp cameraIDI.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cameraIDI.o cameraIDI.cpp

.obj/glwidget.o: glwidget.cpp glwidget.h \
		material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/glwidget.o glwidget.cpp

.obj/model.o: model.cpp model.h \
		vertex.h \
		point.h \
		box.h \
		face.h \
		material_lib.h \
		material.h \
		color.h \
		scene.h \
		objectInstance.h \
		ground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/model.o model.cpp

.obj/objectInstance.o: objectInstance.cpp objectInstance.h \
		point.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		material_lib.h \
		material.h \
		color.h \
		cameraIDI.h \
		scene.h \
		ground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/objectInstance.o objectInstance.cpp

.obj/scene.o: scene.cpp scene.h \
		objectInstance.h \
		point.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		material_lib.h \
		material.h \
		color.h \
		ground.h \
		XML.h \
		tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/scene.o scene.cpp

.obj/face.o: face.cpp face.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/face.o face.cpp

.obj/vertex.o: vertex.cpp vertex.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vertex.o vertex.cpp

.obj/color.o: color.cpp color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/color.o color.cpp

.obj/box.o: box.cpp box.h \
		point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/box.o box.cpp

.obj/XML.o: XML.cpp XML.h \
		tinyxml.h \
		tinystr.h \
		scene.h \
		objectInstance.h \
		point.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		material_lib.h \
		material.h \
		color.h \
		ground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/XML.o XML.cpp

.obj/ground.o: ground.cpp ground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ground.o ground.cpp

.obj/material.o: material.cpp material.h \
		color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/material.o material.cpp

.obj/material_lib.o: material_lib.cpp material_lib.h \
		material.h \
		color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/material_lib.o material_lib.cpp

.obj/point.o: point.cpp point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/point.o point.cpp

.obj/tinystr.o: tinystr.cpp tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tinystr.o tinystr.cpp

.obj/tinyxml.o: tinyxml.cpp tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tinyxml.o tinyxml.cpp

.obj/tinyxmlerror.o: tinyxmlerror.cpp tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tinyxmlerror.o tinyxmlerror.cpp

.obj/tinyxmlparser.o: tinyxmlparser.cpp tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/tinyxmlparser.o tinyxmlparser.cpp

.obj/main.o: main.cpp principal.h \
		.ui/ui_principal.h \
		glwidget.h \
		material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/principal.o: principal.cpp principal.h \
		.ui/ui_principal.h \
		glwidget.h \
		material_lib.h \
		material.h \
		color.h \
		point.h \
		scene.h \
		objectInstance.h \
		model.h \
		vertex.h \
		box.h \
		face.h \
		ground.h \
		cameraIDI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/principal.o principal.cpp

.obj/moc_glwidget.o: .moc/moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_glwidget.o .moc/moc_glwidget.cpp

.obj/moc_principal.o: .moc/moc_principal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_principal.o .moc/moc_principal.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

